name: Terraform Validation CI

on:
  pull_request:
    paths:
      - './production/host_01/**'
      - './production/host_02/**'

permissions:
  contents: write

jobs:
  validation:
    name: Run Validation Checks 
    runs-on: ubuntu-latest

    steps:

    - name: Generate GitHub App Token 🪙
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
      id: generate-token
      with:
        app_id: ${{ secrets.BRAID_BOT_APP_ID }}
        private_key: ${{ secrets.BRAID_BOT_PRIVATE_KEY }}

    - name: Checkout 🔔
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ steps.generate-token.outputs.token }}

    - name: Install Terraform ⛰️
      uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4

    - name: Run TFLint ✅ 
      uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 # v4
      with:
        tflint_version: latest

    - name: Run Terraform fmt ✅
      run: |
        terraform fmt -recursive

    - name: Generate Terraform Docs
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: ./production/host_01, ./production/host_02
        git-push-user-name: "braid-bot[bot]"
        git-push-user-email: "169546839+braid-bot[bot]@users.noreply.github.com"
        output-file: TERRAFORM.md
        output-method: replace
        git-push: "true"
